# Generated by Django 4.1.2 on 2022-11-13 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bp',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinLengthValidator(80), django.core.validators.MaxLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
